### ISSUE TITLE
Ansible 2.0

### ISSUE THREAD

**Issue by NeckBeardPrince** [bushvin/ansible-plugins#1]
Do you know if this would work with Ansible 2.0?

**Comment by bushvin** [comment]
To be honest, I don't know.
I haven't had the time to try it yet, and I don't know when I'll be able to
try it out...
Keep me posted of results if you decide to give it a try?

## 

Sent from my awesome Nexus 5x
On 15 Feb 2016 22:04, "Adam Stracener" notifications@github.com wrote:

> Do you know if this would work with Ansible 2.0?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bushvin/ansible-plugins/issues/1.

## 

Disclaimer http://www.critter.be/maildisclaimer

**Comment by NeckBeardPrince** [comment]
Sure, I'll take a look tonight or tomorrow.
